### ISSUE TITLE
Issue getting muscle to work

### ISSUE THREAD

**Issue by lucienalperstein** [AGIScuipeng/PMPrimer_datasets#1]
Hi there,

I am trying to copy your method from the paper using the _Mycobacteriaceae_groEL2.fasta_ file. before trying to use pmprimer for my own primer design. 

I have successfully used the command:
`pmprimer -f .\Mycobacteriaceae_groEL2.fasta -p` to make the _pmprimer -f .\Mycobacteriaceae_groEL2.filt.fasta_ file.

But when I try to use muscle it does not work. I used the command:
`-f .\Mycobacteriaceae_groEL2.filt.fasta -a muscle`

I am receiving an error message:
`MUSCLE 多序列对比中...
MUSCLE 多序列比对异常`

I have also tried with other fasta files and I receive the same error.

Kindly,
Lucien

**Comment by N3R1UM** [comment]
The 1.0.5 version of PMPrimer does not include the muscle executable file when it is packaged. The 1.0.6 version has included the muscle executable file into the software package.
